IMG_SIZE_X = 346
IMG_SIZE_Y = 260

PROCESSING_SIZE_WIDTH = 240
PROCESSING_SIZE_HEIGHT = 180

X_EDGE = IMG_SIZE_X - PROCESSING_SIZE_WIDTH
Y_EDGE = IMG_SIZE_Y - PROCESSING_SIZE_HEIGHT

PROCESSING_X = X_EDGE // 2
PROCESSING_Y = Y_EDGE // 2
